### ISSUE TITLE
Marker position not quite right after zooming.

### ISSUE THREAD

**Issue by jieter** [marslan390/BeautifyMarker#1]
Had a quick look at your plugin after seeing leaflet/leaflet#4621, but I think it shouldn't look like this after zooming:

![2016-06-03-174607_272x250_scrot](https://cloud.githubusercontent.com/assets/1470389/15784511/2339c4a6-29b3-11e6-92f2-c0070da4e4d7.png)

Chromium 49.0.2623.108 (Developer Build) Ubuntu 15.10 (64-bit)

**Comment by masajid390** [comment]
Ah! it might be some issue with Anchor, i look into it.

**Comment by masajid390** [comment]
issue has been fixed
