### ISSUE TITLE
Is there a way to make the marker bigger?

### ISSUE THREAD

**Issue by astridx** [marslan390/BeautifyMarker#10]
Thank you very much for this plugin. 
I tried it today.
Now I have a question. Can I make a marker bigger?
I tried iconSize, but this does not work for me

Here is my example code:

```
...
options = {
icon: 'plane',
iconShape: 'marker',
borderColor: '#8D208B',
textColor: '#8D208B',
iconSize: '[100, 100]',
backgroundColor: 'transparent'
};
L.marker([50.27264, 8.26469], {
icon: L.BeautifyIcon.icon(options),
draggable: true
}).addTo(mymap).bindPopup("Ich bin ein beautify Marker");
...
```

**Comment by masajid390** [comment]
You can set marker size by changing iconSize to [100, 100] instead of '[100, 100]' and use innerIconStyle property to set font-awesome icon size and position

**Comment by astridx** [comment]
Thank you very much.
