### ISSUE TITLE
Why depend on Bootstrap?

### ISSUE THREAD

**Issue by ruvor** [marslan390/BeautifyMarker#11]
Why do you declare dependency on Bootstrap? As far as I can see the only bootstrapish thing your awesome plugin needs is
```
.beautify-marker {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```
May be you would consider removing such a large dependency and include tiny style rule like mentioned above instead?

**Comment by masajid390** [comment]
yep, thank you. I will fix it shortly.

**Comment by masajid390** [comment]
Fixed
