### ISSUE TITLE
License in package.json

### ISSUE THREAD

**Issue by panta** [marslan390/BeautifyMarker#12]
package.json specify "MAS" as a license (which license is this btw?).
The "license" field [should specify](https://docs.npmjs.com/files/package.json#license) a valid [SPDX license identifier](https://spdx.org/licenses/).
This may seem not so important, but in facts prevents actual usage of the library, since the licensing terms are not clear.

**Comment by masajid390** [comment]
it has been updated, you can check the license info. here (https://opensource.org/licenses/MIT)
Thanks
