### ISSUE TITLE
Custom font icons support

### ISSUE THREAD

**Issue by ghost** [marslan390/BeautifyMarker#14]
Is there a way to support others font icons libraries?
Like material IO, SVG icons, or any custom font icon library?

**Comment by masajid390** [comment]
I have updated the plugin to support custom marker, let's take material IO example:

var options = {
            html: "&lt;i class="material-icons">face</i&gt;",
            iconAnchor: [11, 10]
        };
        L.marker([33.89093747081252, 72.9107666015625], { icon: L.BeautifyIcon.icon(options), draggable: true }).addTo(map).bindPopup("I'm Beautify");

You have you set iconAnchor or other icons property as per in http://leafletjs.com/reference-1.2.0.html#icon
