### ISSUE TITLE
Any way to make a rectangle without icon inside?

### ISSUE THREAD

**Issue by Jonibigoud** [marslan390/BeautifyMarker#18]
Hi, thank you for your work.
Is it possible to generate a "real" rectangle but without any icon in it?

Something like that maybe:

` L.BeautifyIcon.icon({
         icon:'',
         iconShape: 'rectangle',
         backgroundColor: 'grey',
         borderWidth:8'
   })`

Thank you

**Comment by masajid390** [comment]
Hi, sorry for the delay. Yes, you can create a rectangle without icon in it.

 var options = {
          iconShape: 'rectangle-dot',
          iconStyle : 'height:20px;width:20px; border: 2px solid #8A90B4; background-color:transparent;'
        };

        L.marker([33.45, 73.66333007812499], {
          icon: L.BeautifyIcon.icon(options),
          draggable: true
        }).addTo(map).bindPopup("I'm Beautify");


***Note: You can adjust the rectangle height, width, border, background color, and color etc... In other words, you can apply any CSS to the iconStyle property.
