### ISSUE TITLE
Marker Shadow

### ISSUE THREAD

**Issue by futureweb** [marslan390/BeautifyMarker#19]
Hey there,
I wanted to ask if it's possible to add Marker Shadows like in the other Marker Plugins? (Leaflet.awesome-markers plugin v2.0, ...) 
Or is this only possible with Image Markers?
thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by masajid390** [comment]
You can apply shadow by using CSS property (https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow) nothing more than that.
Thanks
