### ISSUE TITLE
Import and use in Angular2 application with ngx-leaflet?

### ISSUE THREAD

**Issue by laurenoldham1202** [marslan390/BeautifyMarker#26]
I am just wondering if anyone has any experience using the BeautifyMarker plugin with the ngx-leaflet Angular2 package. 

I have followed the install instructions alongside the ngx-leaflet plugin instructions [outlined here](https://asymmetrik.com/ngx-leaflet-and-leaflet-plugins/).

In short, I installed the prerequisite packages and imported the styles and scripts in my `angular-cli.json` file, like so:
```
"styles": [
"styles.css",
 "../node_modules/leaflet/dist/leaflet.css",
 "../node_modules/font-awesome/css/font-awesome.css",
 "../node_modules/bootstrap/dist/css/bootstrap.css",
 "../node_modules/beautifymarker/leaflet-beautify-marker-icon.css"
],
"scripts": [
 "../node_modules/leaflet/dist/leaflet.js",
 "../node_modules/beautifymarker/leaflet-beautify-marker-icon.js"
], ...
```

In my app component file, I import leaflet and BeautifyMarker to extend `L.` into the latter, like so:
```
import * as L from 'leaflet';
import 'beautifymarker';
```
Yet trying to access `L.BeautifyIcon` doesn't yield any results. Any help?

**Comment by masajid390** [comment]
@laurenoldham1202 are you able to access L.marker?

**Comment by laurenoldham1202** [comment]
@marslan390 I am. I also posted over on StackOverflow and [apparently someone had luck](https://stackoverflow.com/questions/51679056/add-beautifymarker-plugin-to-ngx-leaflet-project/51703829?noredirect=1#comment90425769_51703829) getting it to work in Angular, but I'm still getting the error `TS2339: Property 'BeautifyIcon' does not exist on type 'typeof "../node_modules/@types/leaflet/index"'`

The leaflet code all works perfectly fine. It seems that it's a typings issue.

**Comment by Jonibigoud** [comment]
Hi, if i can help, here is how i did:

- Installed it through npm:
```
npm install --save leaflet.beautifymarker
```
- added beautifymarker css to "angular.json" file:
```
            "styles": [
              "src/styles.css",
              "node_modules/leaflet.beautifymarker/leaflet-beautify-marker-icon.css"
            ]
```

- added typings to the "typings.d.ts" file:
```
  import * as L from 'leaflet';

  declare module 'leaflet' {

    namespace BeautifyIcon {

      interface BeautifyIconIconOptions extends BaseIconOptions {
        icon?:string,
        iconSize?:any,
        iconAnchor?:any,
        iconShape?:string,
        iconStyle?:string,
        innerIconAnchor?:any,
        innerIconStyle?:string,
        isAlphaNumericIcon?:boolean,
        text?:string,
        borderColor?:string,
        borderWidth?:Number,
        borderStyle?:string,
        backgroundColor?:string,
        textColor?:string,
        customClasses?:string,
        spin?:boolean,
        prefix?:string,
        html?:string
      }

      function icon(options: BeautifyIconIconOptions): Icon;

      class Icon extends L.Icon<BeautifyIconIconOptions> {
          constructor(options?: BeautifyIconIconOptions);
      }
    }
    
  }
```

- Used it with leaflet:
```
    let latlng = L.latLng(feature.geometry.coordinates[1], feature.geometry.coordinates[0]);          
    let myBeautifulIcon= L.BeautifyIcon.icon({
        icon: 'bolt',
        innerIconStyle: 'font-size:1.2em;',
        borderColor: '#0B486B',
        textColor: '#0B486B',
        pane: 'overMarkers'
     })
     let myMarker = L.marker(latlng, { icon: myBeautifulIcon})
```

**Comment by masajid390** [comment]
@laurenoldham1202 If it works for you now, then we can close this issue. Thanks
