### ISSUE TITLE
How to go about changing the icon after instantiating it? 

### ISSUE THREAD

**Issue by jamieodonnell** [marslan390/BeautifyMarker#32]
In a Leaflet Map I have a GeoJSON layer in which I have used pointToLayer to create markers. These are now 'layers' in the GeoJSON layer. 

How do I go through and assign these layers new icons? Say I wanted to switch from one font-awesome marker to another. 

I have seen stackoverflow answers that show how the following could be used: `

geojsonlayer.eachLayer(function (layer) {
layer.setStyle({icon: iconoptions})});

But this doesnt work in practice and I don't know if this is failing due my using of this plugin or more vanilla Leaflet logic. 

Any help greatly appreciated

**Comment by serako** [comment]
Hi,
For changing the standard icon (not GeoJSON) i do that : 
standard declaration
```
options = {
    icon: 'leaf',
    iconShape: 'marker'
};
var marker = L.marker([48.13710, 11.57539], {
    icon: L.BeautifyIcon.icon(options),
    draggable: true
}).addTo(map)
```
and when i want to change : 
```
var icon = marker.options.icon;

icon.options.backgroundColor =  'red';
icon.options.borderColor = 'red';
icon.options.textColor = 'black';

marker.setIcon(icon);
```

**Comment by masajid390** [comment]
@serako answer makes sense. So I am closing it.
