### ISSUE TITLE
How to add own made icons to markers?

### ISSUE THREAD

**Issue by ramonastackoverflow** [marslan390/BeautifyMarker#33]
Couldn't find markers' icons I needed to use, for example 'theatre'. Therefore I've created own icons (.png) to put into markers.  How to do so using this code? 

`    L.BeautifyIcon.icon({   
                        icon: '',                       //this line here
                        iconShape: 'marker',
                        borderColor: '#8d2027',
                        textColor: '#8d2027',
                        backgroundColor: 'transparent',
                    })`

**Comment by masajid390** [comment]
You couldn't add that as mentioned in the plugin description, that plugin generates marker without images.
