### ISSUE TITLE
Install Plugin

### ISSUE THREAD

**Issue by Dasheel** [marslan390/BeautifyMarker#39]
I'm so sorry but I don't understand how to install BeautifyIcon and BeautifyMarker.
I digit "npm install leaflet.beautifymarker" and install is, but whe i refresh tha page: 
`TypeError: Cannot read properties of undefined (reading 'icon')`
`const iconAM = L.BeautifyIcon.icon(options);`
`<Marker icon={iconAM} className={'custom_marker_' + poi.id} position={position} opacity={markerOpacity} id={poi.id}>...`

**Comment by masajid390** [comment]
`npm i beautifymarker` you can see more details [here](https://www.npmjs.com/package/beautifymarker)
