### ISSUE TITLE
Marker angle

### ISSUE THREAD

**Issue by PanBagnat** [marslan390/BeautifyMarker#4]
Hello.

Beautiful plugin but my markers are not vertical (see in attached file).
Do you know why?

Thanks.
![markers](https://cloud.githubusercontent.com/assets/3851596/18480168/f5b03676-79d7-11e6-9792-0a9873e0203b.jpg)

**Comment by masajid390** [comment]
Hello,

Sorry for late, could you please tell me which browser you are using?

**Comment by masajid390** [comment]
There may be one other reason that you off the "zoomend" event of map.

Thanks

**Comment by PanBagnat** [comment]
I was using Chrome. Anyway now I can't use anymore your plugin because I've switch this application to Google maps. Thanks.

**Comment by misikoff** [comment]
I'm having the exact same issue. Marker Icons are 45 degrees off from vertical in every browser that I've tried (Safari, Chrome, and Firefox). Definitely a cool plugin though. Thanks

**Comment by TonivdW** [comment]
I was having the same issue. Turned out that I was using the default leaflet marker with the BeautifyIcon icon. When creating the marker make sure you use L.BeautifyMarker.marker()

**Comment by misikoff** [comment]
Ah, thank you. I'll try that.

**Comment by masajid390** [comment]
@TonivdW is right. You have to create marker using L.BeautifyMarker.marker() instead of default leaflet marker. 

Thanks

**Comment by bloigge** [comment]
@TonivdW  - You Sir saved my day!!

**Comment by agusdutra** [comment]
It's a strange behaviour. I was facing the same issue. I don't want to use the zoomend event and the rotation effect. 
I've removed the zoomend event, but it seems like the markers rotate back to horizontal position on every zoom.. so this _onMapZoomChange is to adjust them vertical back every time they go horizontal. 
Is there a way that the markers show always vertical?
