### ISSUE TITLE
Incomplete, leaflet-beautify-marker.js is missing on github

### ISSUE THREAD

**Issue by wombatstampede** [marslan390/BeautifyMarker#9]
I didn't find leaflet-beautify-marker.js in the master branch although it is required.

I got it from the demo page though.

**Comment by wombatstampede** [comment]
Ok, seems leaflet-beautify-marker.js isn't required anymore since last update. I got it wrong from the demo (which is still using the old syntax)

You can close this and I propose to update the demo site. :-)

**Comment by masajid390** [comment]
Thanks @wombatstampede. Now its been fixed in demo Site.

**Comment by wombatstampede** [comment]
Thank you!
